### ISSUE TITLE
v9: last major version before releasing v10 (hooks)

### ISSUE THREAD

**Issue by jamuhl** [i18next/react-i18next#612]
- [x] keep legacy namings for hoc, render prop
- [x] https://github.com/i18next/react-i18next/issues/451 (no closing tag error)
- [x] https://github.com/i18next/react-i18next/issues/577 (fallback value in Trans)
- [x] https://github.com/i18next/react-i18next/issues/635 (context ponyfill license)

**Comment by jamuhl** [comment]
published react-i18next@9.0.0
